package com.zys.dao;

import com.zys.entitys.ImageInfo;
import com.zys.entitys.ImageInfoKey;

import java.util.List;

public interface ImageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(ImageInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int insert(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int insertSelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    ImageInfo selectByPrimaryKey(ImageInfoKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImageInfo record);

    /**
     * 用户名称查询信息
     *
     * @param name
     * @return
     */
    List<ImageInfo> searchName(String name);
}