package com.zys.dao;

import com.zys.entitys.ImageInfo;

public interface ImageInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int insert(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int insertSelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    ImageInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ImageInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table image_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ImageInfo record);
}