package com.zys.entitys;

import java.sql.Timestamp;
import java.util.Date;

public class PhotoLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    public PhotoLog(Integer id, Timestamp startDate, Timestamp entDate, Timestamp remain, Integer loginId) {
        this.id = id;
        this.startDate = startDate;
        this.entDate = entDate;
        this.remain = remain;
        this.loginId = loginId;
    }

    public Timestamp getStartDate() {
        return startDate;
    }

    public void setStartDate(Timestamp startDate) {
        this.startDate = startDate;
    }

    public Timestamp getEntDate() {
        return entDate;
    }

    public void setEntDate(Timestamp entDate) {
        this.entDate = entDate;
    }

    public Timestamp getRemain() {
        return remain;
    }

    public void setRemain(Timestamp remain) {
        this.remain = remain;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.start_date
     *
     * @mbggenerated
     */
    private Timestamp startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.ent_date
     *
     * @mbggenerated
     */
    private Timestamp entDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.remain
     *
     * @mbggenerated
     */
    private Timestamp remain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.login_id
     *
     * @mbggenerated
     */
    private Integer loginId;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_log
     *
     * @mbggenerated
     */
    public PhotoLog() {
        super();
    }

    @Override
    public String toString() {
        return "PhotoLog{" +
                "id=" + id +
                ", startDate=" + startDate +
                ", entDate=" + entDate +
                ", remain=" + remain +
                ", loginId=" + loginId +
                '}';
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_log.id
     *
     * @return the value of photo_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_log.id
     *
     * @param id the value for photo_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_log.login_id
     *
     * @return the value of photo_log.login_id
     * @mbggenerated
     */
    public Integer getLoginId() {
        return loginId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_log.login_id
     *
     * @param loginId the value for photo_log.login_id
     * @mbggenerated
     */
    public void setLoginId(Integer loginId) {
        this.loginId = loginId;
    }

}