package com.zys.entitys;

import java.util.Date;

public class PhotoLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.start_date
     *
     * @mbggenerated
     */
    private Date startDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.ent_date
     *
     * @mbggenerated
     */
    private Date entDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column photo_log.remain
     *
     * @mbggenerated
     */
    private Date remain;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_log
     *
     * @mbggenerated
     */
    public PhotoLog(Integer id, Date startDate, Date entDate, Date remain) {
        this.id = id;
        this.startDate = startDate;
        this.entDate = entDate;
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table photo_log
     *
     * @mbggenerated
     */
    public PhotoLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_log.id
     *
     * @return the value of photo_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_log.id
     *
     * @param id the value for photo_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_log.start_date
     *
     * @return the value of photo_log.start_date
     *
     * @mbggenerated
     */
    public Date getStartDate() {
        return startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_log.start_date
     *
     * @param startDate the value for photo_log.start_date
     *
     * @mbggenerated
     */
    public void setStartDate(Date startDate) {
        this.startDate = startDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_log.ent_date
     *
     * @return the value of photo_log.ent_date
     *
     * @mbggenerated
     */
    public Date getEntDate() {
        return entDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_log.ent_date
     *
     * @param entDate the value for photo_log.ent_date
     *
     * @mbggenerated
     */
    public void setEntDate(Date entDate) {
        this.entDate = entDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column photo_log.remain
     *
     * @return the value of photo_log.remain
     *
     * @mbggenerated
     */
    public Date getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column photo_log.remain
     *
     * @param remain the value for photo_log.remain
     *
     * @mbggenerated
     */
    public void setRemain(Date remain) {
        this.remain = remain;
    }
}